### ISSUE TITLE
feature request: group by

### ISSUE THREAD

**Issue by juanolon** [k-lar/dynomark#1]
Hi, this looks awesome!
I came to the idea of querying my open todos which this tool. I use one file for each day. So far, it works nice, but I thought grouping the results into its "source" or file would be useful to know from which day the open todo was. something like `group by file` or `..date`.
Thanks :)

**Comment by k-lar** [comment]
Thanks for the request!

I'm not quite sure I understand what exactly you want to do.
Do you want a header with either the filename or file creation date above the results of each different file?

Let's say that you have a folder structure like this:
todos
├── todo-1.md
├── todo-2.md
├── todo-3.md
├── todo-4.md
└── todo-5.md

Something like this:
```dynomark
paragraph from todos/
```
Would you want it to result in something like this?
```md
# todo-1.md

Content from file todo-1.md...

# todo-2.md

Content from file todo-2.md...

...
```

Or would a table query be more suitable for you case? It's not documented anywhere yet but you can now query file "metadata" and get a table as a result.

There's 8 metadata fields that get defined by default for every file that's queried. Those are:
- file.folder (name of the directory where the queried file is located)
- file.path (relative path to the file)
- file.link (a markdown link with the format: `[todo-1.md](todos/todo-1.md)`
- file.size (length in bytes)
- file.ctime (ISO8061 timestamp of creation)
- file.cday (ISO8061 date of creation)
- file.mtime (ISO8061 timestamp when it was last modified, but the modification time/date are exactly the same as creation time/date because go doesn't really support a system agnostic way to do that. Will fix this in an update)
- file.mday (Same as file.cday)

Otherwise you can define your own metadata fields in your files, it works pretty much the same way as dataview for obsidian so you can take a look at their documentation for now while I work on mine: https://blacksmithgu.github.io/obsidian-dataview/annotation/add-metadata/

Here's an example of how a table query looks and works:
```dynomark
TABLE file.cday AS "Date created", title as "Title" FROM todos/
```
Assuming you have a title metadata field somewhere in every todo file, you'll get something like this:
```md
| File      | Date created | Title   |                                                   
|-----------|--------------|---------|                                                   
| todo-1.md | 2024-08-17   | Title 1 |                                                   
| todo-2.md | 2024-08-18   | Title 2 |                                                   
| todo-3.md | 2024-08-19   | Title 3 |                                                   
| todo-4.md | 2024-08-20   | Title 4 |                                                   
| todo-5.md | 2024-08-21   | Title 5 |
```

The file name is by default the first column, if you don't want it to be there, you'd have to use:
```dynomark
TABLE_NO_ID file.cday AS "Date created", title as "Title" from todos/
```
Which would get you:
```md
| Date created | Title   |                                                               
|--------------|---------|                                                               
| 2024-08-17   | Title 1 |                                                               
| 2024-08-18   | Title 2 |                                                               
| 2024-08-19   | Title 3 |                                                               
| 2024-08-20   | Title 4 |                                                               
| 2024-08-21   | Title 5 |
```

You can also use the metadata fields in conditional statements with this syntax (for tables and normal queries):
```dynomark
TABLE_NO_ID file.cday AS "Date created", title as "Title" from todos/ WHERE [title] IS "Title 2"
```
It would result in:
```md
| Date created | Title   |                                                               
|--------------|---------|
| 2024-08-18   | Title 2 |                                                               
```

**Comment by juanolon** [comment]
Ah wow. I didn't knew that obsidian feature. I went through their documentation, and what i meant was: (from https://blacksmithgu.github.io/obsidian-dataview/queries/query-types/#task)

```dataview
TASK
WHERE !completed
GROUP BY file.link
```
[2022-07-30](#) (1)
- [ ] Finish the math assignment
     - [ ] Read again through chapter 3
     - [ ] Write a summary of chapter 1-4

[2022-09-21](#) (2)
- [ ] Buy new shoes #shopping
- [ ] Mail Paul about training schedule

Right now, i''m using `TASK FROM \"$TODOS\" WHERE NOT CHECKED`. Maybe it would work with the table too, but the list view is actually nicer to have (using the vim plugin, it looks as it has been written so)

**Comment by k-lar** [comment]
Ah I see now, I'll try to add this feature soon because I see how that could be very useful! Thanks for bringing it up. I'll comment here (and close this issue) when it's completed so you can get notified.

**Comment by k-lar** [comment]
Took me a bit but I added rough GROUP BY support! You can try it with the latest commit. It works with metadata only, so all the previously stated `file.*` fields work and your user defined metadata should also work. The group by statement comes after the where statement (if there is one) and before the limit statement (although limit doesn't effect the group by results yet).

So you can now do stuff like this (using my previous example folder structure):
`task from todos/ where not checked group by [file.path]`

Would result in this:
```md
- todos/todo-1.md
    - [ ] Task 1
    - [ ] Task 3

- todos/todo-2.md
    - [ ] Item 1

- todos/todo-3.md
    - [ ] Other task 1
    - [ ] Other task 2
```

And you can also do stuff like this:
`task from todos/ where checked
and contains "task" group by [file.path]`

Would result in this:
```md
- todos/todo-1.md
    - [X] Task 2

- todos/todo-3.md
    - [X] Other task 3
```

It works with all normal query types and it doesn't work with table queries.

**Comment by juanolon** [comment]
wow this is awesome. I will try it right now. thanks 💪

**Comment by k-lar** [comment]
I'm finally able to close this issue, I've added limits to groups and their results now.
You can limit the number of groups with this syntax:

`TASK FROM todos/ GROUP BY <number> <metadata_field>` where the number is optional.

That will limit the amount of groups shown in the results. This can be combined with LIMIT at the end of the query, to limit the max amount of results under each group. I also added an example to the README.
